name: Build and publish to docker registry

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.org'
      - 'docs/*'
      - 'docker-compose.yml'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install docker
        uses: papodaca/install-docker-action@main
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: berzdev/fokus:latest
          platforms: 'linux/arm/v7,linux/amd64'