name: Push to github

on:
  push:
    branches:
      - main

jobs:
  push-to-gh:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          repository: berzdev/fokus
          branch: ${{ github.ref }}